### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by gig397** [linkedtales/scrapedin-linkedin-crawler#1]
I am new with Git. So don't know the question answering process here.
But I am having an issue in saving a file.
I have to save all resulting JSON to single CSV.
Can you guys help me with that?

**Comment by leonardiwagner** [comment]
Hi @gig397 , this is the exactly perfect place to ask questions!

> I have to save all resulting JSON to single CSV.
Can you guys help me with that?

Sure, in the `src/saveProfile.js` file you receive the `content` parameter containing all data from a profile to save in any format (JSON, CSV, etc..) , so you could append to your csv file instead of creating a new file to each profile, example:

```javascript
module.exports = (profileId, content, injection) => {
  const { fs, config } = Object.assign({}, dependencies, injection)

  const profileToAppend = `${content.profile.name};${content.profile.headline};${content.profile.location};`
  
  return fs.appendFileSync('your.csv', profileToAppend)
}
```
reference: [How to append to a file in Node?](https://stackoverflow.com/a/11267583/1778285)

Please let me know if it worked for you! :smile:
