### ISSUE TITLE
avoid related profile loop

### ISSUE THREAD

**Issue by jdmin445** [linkedtales/scrapedin-linkedin-crawler#13]
Hi and thank you for your amzing tool!

Sometimes a related profile contain a previously scraped profil. How can we avoid this, because it may loop indefinitely :)

**Comment by leonardiwagner** [comment]
this is quite hard to do in this library since it isn't supposed to save state, eg.: I don't know where are you saving your profiles to check if it was already crawled.

Yes, I could save on memory and that will work on the first run, but if you stop and run again.. this will be useless.

The solution is to place a code on this file, to check if user was already saved on your database, excel, files.. etc: https://github.com/linkedtales/scrapedin-linkedin-crawler/blob/master/src/extractRelatedProfiles.js
