### ISSUE TITLE
Filter profiles to save

### ISSUE THREAD

**Issue by anasdox** [linkedtales/scrapedin-linkedin-crawler#22]
Hello,

relatedProfilesKeywords allow as to filter profiles to crawl and we save all crawled profiles. It will be very usefull to filter profiles to save. what do you think @leonardiwagner ?

**Comment by leonardiwagner** [comment]
Currently, there's  `relatedProfilesKeywords` on `config.json` where you can filter by keywords on related profile description.

Is that what you're looking for, or do you suggest other types of filtering?

**Comment by anasdox** [comment]
### Let take an example : 
A, B, C, D...  are linkedin profiles, where "A" is the root one. let imagine the flowing :
- A.relatedProfiles = [ B, C ]
- B.relatesProfiles  = [ D, E, F, G ]
- B.description  = "CEO Founder"
- E.description  = "DevOps coach"
- F.description  = "DevOps evangelist"

**GOAL** : save only "DevOps" profiles (E and F in our example).

If we use relatedProfilesKeywords = ["DevOps"], E and F will not be scraped because B.description  .contain("DevOps") = false.
 
### The solution
I suggest to create a new one whiteListProfilesKeywords filter list. Only profiles with those Keywords will be saved.

**Comment by leonardiwagner** [comment]
@anasdox You didn't explain how `E` could be checked if even `B` we don't crawl.

Do you mean checking all related profiles anyways, and then we apply the filter on those profiles?

**Comment by anasdox** [comment]
> @anasdox You didn't explain how `E` could be checked if even `B` we don't crawl.

relatedProfilesKeywords = [ ]
whiteListProfilesKeywords = ["devops"]

> Do you mean checking all related profiles anyways, and then we apply the filter on those profiles?

Yes, we should crawl all related profiles and apply whiteListProfilesKeywords filter in "save" action.

**Comment by leonardiwagner** [comment]
> Yes, we should crawl all related profiles and apply whiteListProfilesKeywords filter in "save" action.

Honestly, that doesn't make much sense because if even a related profile doesn't match with your filter, the chance of a related profile of that "unrelated profile" match with your filter is very low.

But the worse problem isn't about the probability itself, it's about time, let's do an example:
- a profile scrap takes ~5 sec. to be scrapped
- a profile on average has 5 related profiles.
- it'll require ~30 sec. to scrap all those profiles you suggest

In 1 hour:
- in the current approach: you scrap 720 **valuable** profiles.
- in your suggested approach: you scrap 120 **valuable** profiles + low chances of scrapping some valuable profiles.

So, it doesn't worth it much, it's better for you to invest more time placing more meaningful `rootProfiles`. But, if you want to do anyways we're glad to receive your contribution to make that an optional feature :smile:
