### ISSUE TITLE
 LinkedIn website changed and scrapedin can't read basic data

### ISSUE THREAD

**Issue by syshex** [linkedtales/scrapedin-linkedin-crawler#27]
Hey there,

Giving a go at this project and got a problem to report :

scrapedin: 2019-10-22T17:06:45.854Z error: [cleanMessageData] LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
2019-10-22T17:06:45.854Z error: error on crawling profile: https://www.linkedin.com/in/XXXXXXXX/ 
 Error: LinkedIn website changed and scrapedin can't read basic data. Please report this issue at https://github.com/linkedtales/scrapedin/issues
(node:20226) UnhandledPromiseRejectionWarning: ReferenceError: relatedProfiles is not defined
    at crawl (/home/rui/TEMP/scrapedin-linkedin-crawler/src/crawler.js:31:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by leonardiwagner** [comment]
Hi @syshex , this message could be using an old `scrapedin` version or due recent LinkedIn change in their layout:
 
1. please confirm in your `package.json` file that scrapedin is using `1.0.10` on `dependencies`:
```
"dependencies": {
    "scrapedin": "1.0.10"
  }
```

run `npm install` to ensure that's version is really installed.

2. I just made a test and it works here if it isn't a version problem, please enter in the profile link that thrown that error and save the *.html file and send me via email at: leonardiwagner @ gmail.com , because it can be a recent regional change, thank you.

**Comment by syshex** [comment]
Hi @leonardiwagner ,

Should have been clear, the test was made yesterday, with and updated git clone of the project. So yes, the dependencies are correct, version 1.0.10.

I'll send you the two profiles that throw the error by email. 

Thanks

**Comment by syshex** [comment]
From checking the code and the DOM of the profile, I believe this is related to this template config

```
peopleAlsoViewed: {
    selector: 'li.pv-browsemap-section__member-container',
    fields: {
      user: {
        selector: 'a',
        attribute: 'href'
      },
      text: 'p'
    }
  },
```

The text, or name, shall we call it, is not on a `<p>` tag.  Maybe, checking the class on the tag that wraps the name will do the trick?

**Comment by syshex** [comment]
@leonardiwagner any ideas on this ?

**Comment by gigaBITE397** [comment]
Hello @syshex ,

I have been through the DOM configuration you provided.
But, the contents are available for the same.

I don't seem to get any issue with that

**Comment by leonardiwagner** [comment]
Sorry for the late response because as @gigaBITE397 said it's working fine for me as well and I gave that low priority.

I suspect there's something different in your regional IP, I asked you to save the page as HTML and send me but you just send the source code.

I really need that you open the page manually in your browser and save as HTML because LinkedIn changes the code a lot via Javascript, that's why just sending the source code as it was is useless for trying to help you.

**Comment by leonardiwagner** [comment]
Closing due to lack of feedback
